### ISSUE TITLE
notes match word that contains annotations

### ISSUE THREAD

**Issue by Mayeu** [vivien/notes#1]
output:
    swatch:11: TODO: _FILE = File.expand_path("~/todo/todo.txt")
    swatch:77: TODO: add todo.txt support

Corresponding file :

```
...
11    TODO_FILE = File.expand_path("~/todo/todo.txt")
...
77            # TODO add todo.txt support
...
```

The first one should not be matched since it's not a todo, but a variable :)

**Comment by vivien** [comment]
Thanks Mayeu for reporting that.
I'll release an update soon.

Regards,
v0n.

**Comment by vivien** [comment]
Hi,

I've fixed this issue. Please update notes with `gem update notes'.

Regards,
v0n.

**Comment by Mayeu** [comment]
Nice,
I'll try this again ;)

Regards,
Mayeu
