### ISSUE TITLE
Silence Binary File Errors by Default

### ISSUE THREAD

**Issue by iloveitaly** [vivien/notes#4]
Great tool!

When I run `notes` in a site directory it throws a bunch of binary file errors. Would be great if the default functionality was to silence these errors (adding the ability to split out errors via `--verbose`). Currently, to avoid this issue I'm running `notes 2>/dev/null`.

**Comment by vivien** [comment]
Good idea. You can run `rake install` from the source directory until I push the next release. Thanks!
